# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    groups:
      dev-tooling:
        patterns:
          - "pestphp/*"
          - "phpstan/*"
          - "larastan/*"
          - "laravel/pint"
          - "orchestra/testbench"
        update-types:
          - "minor"
          - "patch"
      laravel-framework:
        patterns:
          - "laravel/framework"
          - "laravel/scout"
        update-types:
          - "patch"

  - package-ecosystem: "docker"
    directory: "/stubs"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
